### ISSUE TITLE
Final convolutional layer tensor

### ISSUE THREAD

**Issue by ankitdata** [jamesrenhoulee/CancerNet-SCa#2]
Hi @jamesrenhoulee 

Thanks for sharing work.
I am trying to make the activation map to see the important features from your **CancerNet-SCa-A** model

**Que-** is what is final convolutional layer tensor ?

Thanks

**Comment by jamesrenhoulee** [comment]
Hi @ankitdata, 

The final convolutional layer tensor is "probs/Softmax:0"
If you need to find any other tensors, please refer to this document here:

https://github.com/jamesrenhoulee/CancerNet-SCa/blob/main/docs/train_eval_infer.md

Thanks!

**Comment by ankitdata** [comment]
Hi, @jamesrenhoulee 

I tried with "probs/Softmax:0" tensor it doesn't work correctly.

**FYI**-  actually i want to achieve like this done in COVID-Net repo. for grad Cam
https://github.com/lindawangg/COVID-Net/issues/64#issue-618531922

thanks.
waiting for rly

**Comment by jamesrenhoulee** [comment]
Hi @ankitdata,

Thanks for your patience. Please try either `conv5_block3_3_conv/BiasAdd:0`, or `conv5_block3_add/add:0`, similar to in that repo. Let us know the results!

James

**Comment by ankitdata** [comment]
Hi @jamesrenhoulee 

I got heatmap results of input [ex_malignant.jpg](https://github.com/jamesrenhoulee/CancerNet-SCa/blob/3b86235a85678353e0ff6269a37bf65d665e418e/assets/ex_malignant.jpg) image.


**Heatmap image**
![heatmap (3)](https://user-images.githubusercontent.com/50068297/111951453-b3a78980-8b09-11eb-832d-ae0efec199a0.png)

sorry for late reply.
you can close this issue if there is nothing to discuss more on this.

Thanks.!!
